#!/bin/bash
if [ $UID -ne 0 ]
then 
echo
echo "you need to be root"
echo
exit 1
fi
##check number of processor
if [ `nproc` -eq 1 ]
then 
echo "this server is very small"
exit 2
fi
##checking memory
free -m
exit 0
